Feature: Adding Employee to the system

  Background:
    Given I am on Orange Live HRM home page
    And I logged in to the application with credentials as username "Admin" and password "admin123"


  Scenario Outline: Adding the employee to the system
    And I clicked on "PIM" tab
    And I clicked on Add button
    When I enter Employee first name as "<firstName>"
    And I enter Employee last name as "<lastName>"
    And I enter additional text to autogenerated id as abc
    And I click on Create Login Details toggle button
    And I entered the username as "<username>"
    And I selected Enabled radio button
    And I entered password as "<password>"
    And I password entered in confirm password field
    And I clicked on Save button
    Then I should see the verification message "Successfully Saved"
    Examples:
      | firstName | lastName | username | password |
      | Paul      | Collins  | abc      | abcd123  |
      | Cassidy   | Hope     | abc      | abcd123  |
      | Nina      | Patel    | abc      | abcd123  |
      | Odis      | Adalwin  | abc      | abcd123  |
